export const RECEIVE_MAP_DATA = 'RECEIVE_MAP_DATA';

export const SET_VIEWPORT_MATRIX = 'SET_VIEWPORT_MATRIX';
export const MAP_CENTER_POSITION = 'MAP_CENTER_POSITION';
export const MAP_SVG_PAN = 'MAP_SVG_PAN';
export const MAP_SVG_ZOOM = 'MAP_SVG_ZOOM';
export const MAP_SHOW_HOVERTIP = 'MAP_SHOW_HOVERTIP';
export const MAP_MOVE_HOVERTIP = 'MAP_MOVE_HOVERTIP';
export const MAP_HIDE_HOVERTIP = 'MAP_HIDE_HOVERTIP';
export const MAP_SHOW_WIDGET = 'MAP_SHOW_WIDGET';
export const MAP_MOVE_WIDGET = 'MAP_MOVE_WIDGET';
export const MAP_HIDE_WIDGET = 'MAP_HIDE_WIDGET';
export const MAP_SWITCH_IMAGE = 'MAP_SWITCH_IMAGE';
export const RESET_PAN_ZOOM = 'RESET_PAN_ZOOM';

export const FILTER_LOCATION = 'FILTER_LOCATION';
export const CLEAR_SEARCH_TEXT = 'CLEAR_SEARCH_TEXT';
export const DEACTIVATE_SIDEBAR = 'DEACTIVATE_SIDEBAR';
export const ACTIVATE_SIDEBAR = 'ACTIVATE_SIDEBAR';
